# Generated by Django 4.2.20 on 2025-04-05 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_transaction_options_remove_transaction_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
